# Generated by Django 5.0.2 on 2024-02-29 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
