# Generated by Django 5.0.2 on 2024-02-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_management.list",
            ),
            preserve_default=False,
        ),
    ]
