version: "3.7"
networks:
  tms_net:
    driver: bridge
    name: tms_net

services:
  lb_server:
    image: haproxy:2.7
    container_name: lb_server
    hostname: lb_server
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - tms_net
    depends_on:
      - tms_server
    ports:
      - 8001:80

  tms_server:
    image: tms_server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms_server
    hostname: tms_server
    restart: unless-stopped
    volumes:
      - ./src:/src
    networks:
      - tms_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
