version: "3.7"
networks:
  tms_net:
    driver: bridge
    name: tms_net

services:
  proxy_server:
    image: haproxy:2.7
    container_name: proxy_server
    hostname: proxy_server
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - tms_net
    ports:
      - 8001:80

  tms_server:
    image: tms_server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms_server
    hostname: tms_server
    restart: unless-stopped
    volumes:
      - ./src:/src
    networks:
      - tms_net
