name: Deploy docs to gh-pages

on:
  - push

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
