name: Deploy Task MS docs to pages

on:
  push:
    branches: [master]

jobs:
  build_deploy_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html
      - name: Init new repo in dist folder & commit generated files
        run: |
          cd docs/_build/html
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "extinctCoder@outlook.com"
          git config --local user.name "extinctCoder"
          git commit -m "Sphinx docs deploy"

      - name: Force push to destination folder
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
