name: Run Django unitest

on:
  - push

jobs:
  django_unitest:
    # runs-on: [Linux, x64, Self-hosted]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pipenv for venv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv lock && pipenv install --system --deploy

      - name: Run database migrations
        run: |
          cd src
          python manage.py makemigrations
          python manage.py migrate

      - name: Run unit tests
        run: |
          pipenv run python manage.py test
